# Copyright 2019 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: release-draft
spec:
  params:
  - name: package
    description: package (and its children) under test
  - name: git-revision
    description: the git revision of the release
  - name: release-name
    description: The name of the release (e.g. Cat + Robot for pipeline)
  - name: release-tag
    description: Release number and git tag to be applied (e.g. v0.888.1, with 'v')
  - name: previous-release-tag
    description: Previous release number - for author and PR list calculation
  - name: bucket
    description: GCS bucket where to get the release files from (e.g. gs://tekton-releases/pipeline)
  - name: rekor-uuid
    description: The Rekor UUID associated to the attestation
  workspaces:
    - name: shared
      description: Workspace where the git repo is prepared for testing
    - name: credentials
      description: GCS credentials
  tasks:
    - name: clone-repo
      taskRef:
        resolver: bundles
        params:
          - name: bundle
            value: gcr.io/tekton-releases/catalog/upstream/git-clone:0.5
          - name: name
            value: git-clone
          - name: kind
            value: task
      params:
        - name: url
          value: https://github.com/$(params.package)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: shared
          subPath: repo
    - name: clone-bucket
      taskRef:
        resolver: bundles
        params:
          - name: bundle
            value: gcr.io/tekton-releases/catalog/upstream/gcs-download:0.1
          - name: name
            value: gcs-download
          - name: kind
            value: task
      params:
        - name: path
          value: .
        - name: location
          value: $(params.bucket)/previous/$(params.release-tag)
        - name: typeDir
          value: "true"
      workspaces:
        - name: output
          workspace: shared
          subPath: release
        - name: credentials
          workspace: credentials
    - name: create-draft-release
      runAfter: ['clone-repo', 'clone-bucket']
      taskRef:
        resolver: git
        params:
          - name: org
            value: tektoncd
          - name: repo
            value: plumbing
          - name: revision
            value: main
          - name: pathInRepo
            value: tekton/resources/release/base/draft_release_task.yaml
      workspaces:
        - name: shared
          workspace: shared
      params:
        - name: package
          value: $(params.package)
        - name: git-revision
          value: $(params.git-revision)
        - name: release-name
          value: $(params.release-name)
        - name: release-tag
          value: $(params.release-tag)
        - name: previous-release-tag
          value: $(params.previous-release-tag)
        - name: rekor-uuid
          value: $(params.rekor-uuid)
